### ISSUE TITLE
Filtering images by path -- possible without the Url key?

### ISSUE THREAD

**Issue by Vacilando** [robinmetral/gatsby-source-s3#184]
Contrary to https://github.com/DSchau/gatsby-source-s3 this plugin supports more than 1000 items in a bucket which is GREAT so we planned to switch all our projects to this one.

However, it does not have Url as a key.

This seems to be a major problem since we often need to show only images on certain paths (folders) in the bucket.

It there a way to do it in V2?

Or do we have to downgrade to 1.2.0?
Will V1 continue being supported along V2?

**Comment by robinmetral** [comment]
Hi @Vacilando, thanks for giving the plugin a try!

Removing the `Url` key was a [breaking change in v2](https://github.com/robinmetral/gatsby-source-s3/releases/tag/v2.0.0) - I couldn't see a use case for it. Filtering by path makes sense, though.

But I'm wondering - Could we filter by folder using the keys themselves? Unless I'm missing something, key names for a nested structures should look like this:

```
RootPhoto.jpg
photos/2020/January/JanuaryPhoto.jpg
photos/2020/February/FebruaryPhoto1.jpg
photos/2020/February/FebruaryPhoto2.jpg
photos/2020/February/FebruaryPhoto3.jpg
```

If this is right, we should be able to filter only objects in the `photos` folder with GraphQL.

(The S3 `ListObjectsV2` API –the one we're using to get the objects– actually exposes a `prefix` field for this: [example](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_Example_5). Maybe this plugin could also expose it in the future to make queries more fine-grained.)

Of course if the URL is a must have, let's reintroduce it 🙂 I'm happy to review a PR for this, or I can tackle it myself (next week).

Let me know if filtering by key would work for you. In the meantime, if you want to try out the plugin using URLs, you can:

1. use the `url` key, it contains the pre-signed URL and you should be able to use it for filtering (it's the same as the object URL but with a token in URL params). I don't recommend this long-term though, because this pre-signed URL is only intended for internal use
2. give a try to v1.2 and upgrade later. I'm not planning on maintaining legacy versions, but it should still work fine at the moment

Take care!

**Comment by Vacilando** [comment]
@robinmetral thanks for your clear answer!
- You were right; filtering by key "Key" achieves the same goal. 
- And, using keys "Key" and "Bucket" can one reconstruct the full URL if need be.
