### ISSUE TITLE
localFile does not appear in graphiQL

### ISSUE THREAD

**Issue by ciprian97** [robinmetral/gatsby-source-s3#23]
Hello, I want to get the images from my aws S3 cloud and I'm using this plugin from gatsby. But I can't query them because the localFile doesn't exist. 

Here is the configuration from gtabsy-config.js
```
{
      resolve: `@robinmetral/gatsby-source-s3`,
      options: {
        aws: {
          accessKeyId: 'my accessKeyId',
          secretAccessKey: 'my secretAccessKey',
          region: 'eu-central-1',
        },
        buckets: ['my bucket (only one bucket)'],
      },
    },
```
I have the following s3 configuration:
-S3 bucket is private 
-only read acces based on IAM user 
-region is 'eu-central-1'

**Comment by robinmetral** [comment]
Hi @ciprian97, thanks for reporting!

In theory this should work, but I haven't tested this plugin with private buckets yet. I'm guessing that this is the issue here.

From the README:

> Currently, your buckets will need to be configured for public access with this access policy: (add your bucket name under `Statement.Resource`)
> 
>     {
>       "Version": "2008-10-17",
>       "Statement": [
>         {
>           "Sid": "AllowPublicRead",
>           "Effect": "Allow",
>           "Principal": {
>             "AWS": "*"
>           },
>           "Action": "s3:GetObject",
>           "Resource": "arn:aws:s3:::my-bucket/*"
>         }
>       ]
>     }

For now, you should be able to make this work by making your bucket public, as described above ☝️ 

Sourcing from private buckets is definitely an important feature, so I'll try it out on my end, and see if there's anything I need to add to the plugin in order to handle them.

You can expect an update from me sometime this week. And of course if you're up for it, feel free to open a PR yourself!

**Comment by ciprian97** [comment]
Thank you @robinmetral, I will change the bucket to be public.

**Comment by robinmetral** [comment]
Great, let me know if you still run into issues! I'll look into supporting private buckets on my end 🙂

**Comment by ciprian97** [comment]
After I changed the bucket from private to public, the localFile is still not there.

**Comment by robinmetral** [comment]
Ah, it's something else then, thanks for trying! A few more questions to try to debug:

* are you getting any console output during `gatsby develop`, any info or errors besides the one telling you that `localFile` is undefined?
* is there at least one object in the bucket, like a jpg or png image? (I'm guessing there is, just checking 🙂). `localFile` will only exist if the image is transformed successfully (after it's been pulled)
* Related to the point above ☝️: can you query the objects in GraphiQL?

If I could look into your code, it would make things much simpler to debug. Could you maybe make a reproduction repo, making sure not to disclose your AWS credentials (i.e. use env vars)? We can also have a quick pairing session sometime this week if it helps.

It might also help to look into [robinmetral/eaudepoisson.com](https://github.com/robinmetral/eaudepoisson.com), I'm using the plugin successfully over there.

**Comment by ciprian97** [comment]
I created a repo https://github.com/ciprian97/reproduction with what configuration I have. Also I checked your repo robinmetral/eaudepoisson.com and it seems to be the same configuration for gatsby-source-s3

**Comment by robinmetral** [comment]
@ciprian97 I just cloned your repo and added my own AWS config with a test bucket, and it works fine. This tells me your issue is probably on the AWS side of things.

Can you check a couple more things:

1. **Does your bucket contain non-image files?** `localFile` will only be defined for images - it's for the files transformed by sharp. For the record, this happens in Gatsby's `onCreateNode` method:
https://github.com/robinmetral/gatsby-source-s3/blob/ec9fc17b4a99c96d4008a79d8bdafa6f61afc80b/src/gatsby-node.ts#L124
For non-image files, it will be `null`, so you need to check it's defined before rendering. Something like this:
    ```javascript
    // let's say `objects` contains all your S3Object nodes and you want to loop through all images
    objects.map(object => {
      if (object.localFile) { // without this condition you'll get an error for non-image files
        return (
          <Img fluid={object.localFile.childImageSharp.fluid} />
        )
      }
    }
    ```
2. **Check your S3 bucket and IAM role policies**. For my test account, I have:

    **S3 bucket policy** (public)
    ```json
    {
      "Version": "2008-10-17",
      "Statement": [
        {
          "Sid": "AllowPublicRead",
          "Effect": "Allow",
          "Principal": {
            "AWS": "*"
          },
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::MY_BUCKET_NAME/*"
        }
      ]
    }
    ```

    **IAM role access policy** (get and list access to multiple buckets)
    ```json
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "VisualEditor0",
          "Effect": "Allow",
          "Action": [
            "s3:Get*",
            "s3:List*"
          ],
          "Resource": [
            "arn:aws:s3:::MY_BUCKET_NAME",
            "arn:aws:s3:::ANOTHER_BUCKET_NAME"
          ]
        }
      ]
    }
    ```

I hope this helps! Let me know if you manage to fix your issue 🙂

**Comment by rastann** [comment]
Hi Robin
I have the same issue as Ciprian has, but on my side, the bucket is private.
In my s3 configurations, I have the following:

- Block all public access is set ON
- And bucket policy is not set. (empty body)

Could you please tell me if this plugin is working also with a private bucket, and access to it is based on the AWS credentials ?

Thank you

**Comment by ciprian97** [comment]
@robinmetral you are right, the problem was in my s3 configuration, now the localFile appear and I can query the images.
Thank you!

**Comment by robinmetral** [comment]
Happy to hear! Feel free to open a new issue if something else comes up 🙂
