### ISSUE TITLE
Sourcing markdown files from S3

### ISSUE THREAD

**Issue by Sara14-sudo** [robinmetral/gatsby-source-s3#505]
I am doing a blog project.
 I am doing it to read dynamically from S3 bucket. i am using plugin is /plugins/@robinmetral/gatsby-source-s3/
in s3 bucket
 There is bucket named tia , there is a file named post-1.md, its a markdown file.
In post-1.md there is title, featured img URL, date and content. While using  Alls3object query  
I am getting displayed bucket name, key, URL only. 

What I need is a query to display title, content, featured img URL from post 1.md.
We are not getting any query,  help me  please
Please help me ASAP, my project is getting stuck with this.

**Comment by Sara14-sudo** [comment]
I am doing a blog project.
 I am doing it to read dynamically from S3 bucket. i am using plugin is /plugins/@robinmetral/gatsby-source-s3/
in s3 bucket
 There is bucket named tia , there is a file named post-1.md, its a markdown file.
In post-1.md there is title, featured img URL, date and content. While using  Alls3object query  
I am getting displayed bucket name, key, URL only. 

What I need is a query to display title, content, featured img URL from post 1.md.
We are not getting any query,  help me  please
Please help me ASAP, my project is getting stuck with this.

**Comment by robinmetral** [comment]
Hey @Sara14-sudo, thanks for your question!

Currently, the plugin only downloads image files locally, as you can see here:

https://github.com/robinmetral/gatsby-source-s3/blob/029d2db2d610d18b84ded89282a7fd6a6ee648a4/src/gatsby-node.ts#L125

So if you add non-image files —like Markdown files— to your buckets, you'll get the AWS presigned URL for them, but not the file content. (You can always explore the data that was downloaded in your [local GraphQL UI](http://localhost:8000/___graphql)).

On top of my head, I don't know of other Gatsby S3 plugins that support this. The challenge is that different file formats require different Gatsby transformer plugins (like sharp for images).

If supporting it wouldn't make the plugin overly complicated —otherwise I'd recommend using a separate plugin for sourcing non-image S3 objects— we could look into implementing it. PRs welcome!

**Comment by Sara14-sudo** [comment]
could you please  tell me  which plugin should i use to
read non-image file (markdown file) content from s3 bucket


pls, reply with example  or reference

**Comment by robinmetral** [comment]
> could you please  tell me  which plugin should i use

I don't know, as mentioned in my message above. You could search the Gatsby plugins  directory.

> pls, reply with example or reference

Sorry, but no. This is an open-source plugin that I maintain in my spare time, and although I am committed to making it as useful as possible to the community, I don't have time to write examples or do research for different use cases than those documented in the `README`.

---

I'll close this for now, since sourcing Markdown is unsupported by the plugin and doesn't seem to be requested by other users. To anyone reading this: if you're interested in this functionality, please comment in this thread with your use case, and we can discuss implementation together 🙂

**Comment by Sara14-sudo** [comment]
please comment in this thread with your use case, and we can discuss implementation together.
ok Thank You, Sir,

Our Gatsby application have got blog page as well. Content writers will be writing the blogs. We cannot have the blog markdown file part of gatsby project because we have to provide source code of our application/website to content writers. They are not familiar with either visual studio or code repository eventhough we have got CI/CD on aws for our gatsby application.

So we decided to provide an interface to upload blog markdown file to our aws s3 bucket.

we will be keep adding new blogs part of the gatsby application.

So when some one saves the new blog markdown files (multilingual) on s3, need to trigger the aws amplify ci/cd.

In worst case if autotriggering doesn't happen, we can just give new build command through our aws amplify console. But when build happends, it should download the blog markdown file from s3 to make blogs part of gatsby application.

**Comment by Sara14-sudo** [comment]
**I am doing it in the following way:**
I created a bucket named ABCD, 
i have uploaded, post1.md, post2.md, etc.

post-1.md
---
title: My first blog post!
featuredImgUrl: https://images.unsplash.com/photo-1560237731-890b122a9b6c
featuredImgAlt: Mountains with a starry sky
---
Hello World

I used the plugin is  @robinmetral/gatsby-source-s3

I used  allS3Object  
 I am getting displayed bucket name, key, URL only.
What I need is a query to display Title, Content, featured img URL , from post 1.md.
We are not getting any query, help me please

help please, my project is stuck with this

**Comment by Sara14-sudo** [comment]
Sir , Please help ,  @robinmetral

**Comment by robinmetral** [comment]
As I mentioned [too](https://github.com/robinmetral/gatsby-source-s3/issues/505#issuecomment-915904529) [many](https://github.com/robinmetral/gatsby-source-s3/issues/505#issuecomment-915965338) [times](https://github.com/robinmetral/gatsby-source-s3/issues/509), this is not possible at the moment. I don't have time to look into this myself right now. You're welcome to submit a pull request if you'd like to contribute.

Please do not open any further issues, or I'll have to report your accounts to GitHub.
